### ISSUE TITLE
disk size should check $SNAP_DATA, not /var/lib/snapd/hostfs

### ISSUE THREAD

**Issue by ogra1** [ogra1/fabrica#35]
In the new system monitor the disk size is always 100% on core.
This is because it checks the size of /var/lib/snapd/hostfs which corresponds to / ... which in turn is /dev/loop0 (the core snap) outside of confinement. Being a squashfs this is indeed always at 100%. 

To get the correct data the code should rather use $SNAP_DATA for checking:

    ogra@pi4:~$ sudo snap run --shell fabrica.web -c 'df -h $SNAP_DATA'
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/sda1       458G   68G  367G  16% /var/snap

**Comment by slimjim777** [comment]
Okay, this was tested on classic only

**Comment by ogra1** [comment]
this is fixed in https://github.com/ogra1/fabrica/pull/37
