### ISSUE TITLE
stuck at waiting on network

### ISSUE THREAD

**Issue by kz6fittycent** [ogra1/fabrica#50]
Currently, I'm using `fabrica` to build some snaps locally and I am stuck at `waiting on network`. I've got port 8000 open on the host but not on my ext firewall. If I open that port, then I can see/configure everything from the www. I don't think that's a great idea. 

Did I miss something in the documentation? 

TIA.

![Screenshot from 2020-11-18 13-23-51](https://user-images.githubusercontent.com/14829816/99577769-6e2f5000-29a1-11eb-9080-637cb204b1df.png)

**Comment by ogra1** [comment]
hmm, yeah, this should eventually time out and fail (indeed full network access is a hard requirement to pull in build-packages/stage-packages, build-snaps/stage-snaps and snapcraft itself from the ubuntu archive and the snap store)

**Comment by kz6fittycent** [comment]
Yeah it hung there for hours. I'm removing both `lxd` and `fabrica` and will try starting over again. Just retracing my steps.

**Comment by kz6fittycent** [comment]
Same situation. I'm at a loss. This is great though and thanks for creating this snap. It's possible that my system is to blame but hard to tell. 

This popped up and I got lucky enough to catch it: `Error:logs: sql: no rows in result set`

Then I got the `lxd` logs:
```
sudo tail -f /var/snap/lxd/common/lxd/logs/lxd.log
t=2020-11-19T10:16:58-0600 lvl=info msg="Creating container" ephemeral=false name=mc-installer-1605802618 project=default
t=2020-11-19T10:16:59-0600 lvl=info msg="Created container" ephemeral=false name=mc-installer-1605802618 project=default
t=2020-11-19T10:17:08-0600 lvl=info msg="Starting container" action=start created=2020-11-19T10:16:58-0600 ephemeral=false name=mc-installer-1605802618 project=default stateful=false used=1969-12-31T18:00:00-0600
t=2020-11-19T10:17:08-0600 lvl=info msg="Started container" action=start created=2020-11-19T10:16:58-0600 ephemeral=false name=mc-installer-1605802618 project=default stateful=false used=1969-12-31T18:00:00-0600
t=2020-11-19T10:25:55-0600 lvl=info msg="Pruning expired instance backups" 
t=2020-11-19T10:25:55-0600 lvl=info msg="Done pruning expired instance backups" 
```

No idea otherwise.

**Comment by kz6fittycent** [comment]
it's definitely something with this server - just installed it on a desktop PC and it's working
