### ISSUE TITLE
Core20 support?

### ISSUE THREAD

**Issue by kz6fittycent** [ogra1/fabrica#53]
I've been attempting to build a `core20` snap using Fabrica and I keep getting the following error (`core20` is installed on the host):

```
Cloned repo: /var/snap/fabrica/common/c1add57lorv0pt52krm0 (b45989a9e01468036ec6686ea45947d0d36882d3)

snapcraft.yaml: /var/snap/fabrica/common/c1add57lorv0pt52krm0/snapcraft.yaml

Distro: focal

Creating and starting container

Create container mc-server-installer-1617227921

No such object
```

Any ideas if this is the snap or something else?

**Comment by ogra1** [comment]
hey, sorry for the long delay in answering ... this is indeed a shortcoming of fabrica ... i just added core20 support, but sadly the builds fail for everything but amd64 and arm64 ...
these two arches in the edge channel should have core20 support though ... trying to fix the other builds now (some unrelated python module seems to have vanished from pypi)

**Comment by kz6fittycent** [comment]
Oh awesome man! I'll do some testing - I'm only building on amd64 anyway. I'll get back with you if you'd like.

**Comment by kz6fittycent** [comment]
It's getting stuck during the build on "waiting on network" - see screenshot. 
![Screenshot from 2021-05-14 12-31-30](https://user-images.githubusercontent.com/14829816/118307680-a4f9a500-b4b0-11eb-8705-2b66df1c9d55.png)

I went to go find logs, but I'm not sure where they're located. 

I tried using `snap run fabrica` but that failed with `fabrica: command not found`. If you give me some direction, I'll keep going with testing and see what I uncover.

**Comment by ogra1** [comment]
try re-running the init tool:
```
sudo snap restart fabrica.init
```
(if you reload the web page after this command you should see it creating a focal image there too)
i probably need to run it from an upgrade hook

**Comment by kz6fittycent** [comment]
Unfortunately, the same thing is occurring. Not sure what would cause it. 

I can try purging everything (no big deal) and reinstalling both lxd and fabrica (edge).

**Comment by ogra1** [comment]
weird, it definitely works for me on two installs with the latest package (where i added a post-refresh hook). do you see a fabrica-focal image in ```lxc image list``` ?

there shouldn't be a need to purge everything, but you could try to wipe the existing fabrica-focal image (```lxc image delete fabrica-focal```) if there is one, in case it was not fully set up ... and then manually re-run the init service from above

**Comment by kz6fittycent** [comment]
Some odd behavior here...

NOTE: 
I ended up purging everything and starting over. Had to init the `fabrica-focal` image to even get ANY images to show up in the list. But was still getting `Waiting for the network`. 

I double-checked `ufw` to ensure that port 80 was allowed - it is. So then I disabled `ufw` and it's working now. Which means there's something odd going on there. Port 80 is default (AFAIK) but there must be something going on with the `lxd` snap. Not sure. Anyway, I'm building a `core20` snap right now. 

All the snap connections are in place per your instructions on this [page](https://snapcraft.io/fabrica). 

```
sudo lxc image list
+----------------+--------------+--------+-------------------------------------------+--------------+-----------+----------+------------------------------+
|     ALIAS      | FINGERPRINT  | PUBLIC |                DESCRIPTION                | ARCHITECTURE |   TYPE    |   SIZE   |         UPLOAD DATE          |
+----------------+--------------+--------+-------------------------------------------+--------------+-----------+----------+------------------------------+
| fabrica-bionic | d772aa759901 | no     | ubuntu 18.04 LTS amd64 (daily) (20210514) | x86_64       | CONTAINER | 192.00MB | May 17, 2021 at 3:44pm (UTC) |
+----------------+--------------+--------+-------------------------------------------+--------------+-----------+----------+------------------------------+
| fabrica-focal  | a5787a028202 | no     | ubuntu 20.04 LTS amd64 (daily) (20210513) | x86_64       | CONTAINER | 358.26MB | May 17, 2021 at 3:44pm (UTC) |
+----------------+--------------+--------+-------------------------------------------+--------------+-----------+----------+------------------------------+
| fabrica-xenial | 1b6a6d7a59eb | no     | ubuntu 16.04 LTS amd64 (daily) (20210429) | x86_64       | CONTAINER | 170.57MB | May 17, 2021 at 3:44pm (UTC) |
+----------------+--------------+--------+-------------------------------------------+--------------+-----------+----------+------------------------------+
```

**Comment by kz6fittycent** [comment]
I think we can close this unless you'd like more info from me.

**Comment by ogra1** [comment]
no this is fine and it is indeed likely that lxd might need more than port 80 to properly run the containers ... closing, thanks for the feedback !!
